### PR TITLE
docs: fs already defined in example

### PR DESCRIPTION
**Pull request by SgtPooki**
Fixes non-compileable code example where we set both `node:fs` import and `unixfs(helia)` to a variable `fs`.

### CODE REVIEW

**Comment by SgtPooki** [comment]
ping @achingbrain, I don't have permissions to assign review to you nor merge this.

**Review by achingbrain — APPROVED** [review]

**Comment by achingbrain** [comment]
I've added @ipfs/helia-dev to this repo - you should have perms now 👍

**Comment by achingbrain** [comment]
Nb. I changed the PR title from `fix:` to `docs:` because otherwise it'll appear in the bugfix section of the release notes.

**Comment by SgtPooki** [comment]
kicked off a retry of https://github.com/ipfs/helia-car/actions/runs/5447973595/attempts/1

**Pull request merged**
